### ISSUE TITLE
Full Rect and Fit Parent

### ISSUE THREAD

**Issue by rpxomi** [GDquest/godot-3-guides#10]
In the tutorial show this...
![tutorial](https://user-images.githubusercontent.com/31228150/39166760-d5a6d1ba-4761-11e8-95d0-8fcaceb66e87.png)

Where is: **Full Rect and Fit Parent**?
![layout](https://user-images.githubusercontent.com/31228150/39166686-62dacc86-4761-11e8-847b-2a97e4f2f8d7.png)

Version
![version](https://user-images.githubusercontent.com/31228150/39166694-6d5d9c38-4761-11e8-84e7-664699d657c6.png)

**Comment by NathanLovato** [comment]
Please read the tutorials in the official docs: http://docs.godotengine.org/en/latest/getting_started/step_by_step/ui_game_user_interface.html

This repository is just for work in progress work:

![image](https://user-images.githubusercontent.com/12694995/39170420-6f314526-47d6-11e8-96b4-6950e71bf652.png)

**Comment by rpxomi** [comment]
I'm sorry, but I'm following the Step by Step from the official Godot website and show that option: Full Rect and Fit Parent

If you are not responsible for writing those tutorials, then who is it? So I stop commenting here.

**Comment by rpxomi** [comment]
I'm sorry, but I'm following the step-by-step tutorial on the official Godot website and it shows that option: **Full Rect and Fit Parent**, and that link shows the same option. Have you read it?

I want to follow the tutorial and I can not do it for things like that. If you are not responsible for writing those tutorials, who is it? To stop writing comments here and not to disturb it.

**Comment by rpxomi** [comment]
I'm sorry, but I'm following the step-by-step tutorial on the official Godot website and it shows that option: **Full Rect and Fit Parent**, and that link shows the same option. Have you read it?

If you are not responsible for writing those tutorials, who is it? That way, I stop writing comments here and I do not bother you.

**Comment by NathanLovato** [comment]
No worries, you're not bothering me. But yeah if there's a pb with the official docs you can open the issue in the docs repository directly. I saw you did, thanks!
