### ISSUE TITLE
Style guide additions

### ISSUE THREAD

**Issue by cbscribe** [GDquest/godot-3-guides#5]
We need a standard for writing arguments. Looking at the docs and recent PRs now, I see:

- `argument`
- 'argument'
- "argument"
- [i]argument[/i]
- [code]argument[/code]

**Comment by NathanLovato** [comment]
'argument' is the one I've seen the most. I wish it was markdown and we could use \`\`, as bbcode is less convenient to write, and more importantly edit. I'd go with [code] as it's code, after all. What do you think?

**Comment by cbscribe** [comment]
I agree. [code] is the way I did it in all my docs.

**Comment by cbscribe** [comment]
This version has diverged from the updated one in your PR. We probably shouldn't link people here anymore.
